set PROCESSING_LIBRARY=4
ruby parseMP.rb 1 %PROCESSING_LIBRARY%
ruby parseMP.rb 6 %PROCESSING_LIBRARY%
ruby parseMP.rb 8 %PROCESSING_LIBRARY%
ruby parseMP.rb 4 %PROCESSING_LIBRARY%
ruby parseMP.rb 5 %PROCESSING_LIBRARY%
ruby parseMP.rb 7 %PROCESSING_LIBRARY%
ruby parseMP.rb 3 %PROCESSING_LIBRARY%
ruby parseMP.rb 2 %PROCESSING_LIBRARY%
set PROCESSING_LIBRARY=5
ruby parseMP.rb 1 %PROCESSING_LIBRARY%
ruby parseMP.rb 6 %PROCESSING_LIBRARY%
ruby parseMP.rb 8 %PROCESSING_LIBRARY%
ruby parseMP.rb 4 %PROCESSING_LIBRARY%
ruby parseMP.rb 5 %PROCESSING_LIBRARY%
ruby parseMP.rb 7 %PROCESSING_LIBRARY%
ruby parseMP.rb 3 %PROCESSING_LIBRARY%
ruby parseMP.rb 2 %PROCESSING_LIBRARY%
pause