# encoding: UTF-8

@zenbu_category_to_garmin_category = {
'BedAndBreakfast' => '0x2b02', #Accommodation - Bed & Breakfast Inn 0x2b02
'RVPark' => '0x2b03', #Accommodation - Camping RV Park 0x2b03
'Campground' => '0x2b03', #Accommodation - Camping RV Park 0x2b03
'Hotel' => '0x2b01', #Accommodation - Hotel - Motel 0x2b01
'Motel' => '0x2b01', #Accommodation - Hotel - Motel 0x2b01
'Hostel' => '0x2b00', #Accommodation 0x2b00
'LodgingBusiness' => '0x2b00', #Accommodation 0x2b00
'AmusementPark' => '0x2c01', #Attractions - Amusement Theme Park 0x2c01
'StadiumOrArena' => '0x2c08', #Attractions - Arena Stadium Track Raceway 0x2c08
'LandmarksOrHistoricalBuildings' => '0x2c04', #Attractions - Landmark 0x2c04
'Library' => '0x2c03', #Attractions - Libraries 0x2c03
'Museum' => '0x2c02', #Attractions - Museum History 0x2c02
'Park' => '0x2c06', #Attractions - Park 0x2c06
'Winery' => '0x2c0a', #Attractions - Vineyard Winery 0x2c0a
'Zoo' => '0x2c07', #Attractions - Zoo 0x2c07
'TouristAttraction' => '0x2c00', #Attractions 0x2c00
'AutoDealer' => '0x2F07', #Auto - Car Dealer Autoparts 0x2F07
'AutoPartsStore' => '0x2F07', #Auto - Car Dealer Autoparts 0x2F07
'MotorcycleDealer' => '0x2F07', #Auto - Car Dealer Autoparts 0x2F07
'AutoRental' => '0x2F02', #Auto - Car Rental 0x2F02
'AutoWash' => '0x2F0E', #Auto - Car Wash 0x2F0E
'GasStation' => '0x2f01', #Auto - Fuel petrol stations 0x2f01
'ParkingFacility' => '0x2f0b', #Auto - Parking 0x2f0b
'AutoBodyShop' => '0x2f03', #Auto - Repair 0x2f03
'AutoRepair' => '0x2f03', #Auto - Repair 0x2f03
'MotorcycleRepair' => '0x2f03', #Auto - Repair 0x2f03
'TireShop' => '0x2f', #Automotive 0x2f
'AutomotiveBusiness' => '0x2f', #Automotive 0x2f
'Airport' => '0x2f04', #Aviation - Airport 0x2f04
'BuddhistTemple' => '0x6404', #Church place of worship 0x6404
'CatholicChurch' => '0x6404', #Church place of worship 0x6404
'Church' => '0x6404', #Church place of worship 0x6404
'HinduTemple' => '0x6404', #Church place of worship 0x6404
'Mosque' => '0x6404', #Church place of worship 0x6404
'PlaceOfWorship' => '0x6404', #Church place of worship 0x6404
'Synagogue' => '0x6404', #Church place of worship 0x6404
'BarOrPub' => '0x2d02', #Entertainment - Bar 0x2d02
'NightClub' => '0x2d02', #Entertainment - Bar 0x2d02
'ComedyClub' => '0x2d02', #Entertainment - Bar 0x2d02
'Casino' => '0x2D04', #Entertainment - Casino 0x2D04
'MovieTheater' => '0x2d03', #Entertainment - Cinema 0x2d03
'PerformingArtsTheater' => '0x2d01', #Entertainment - Theatre 0x2d01
'EntertainmentBusiness' => '0x2d', #Entertainment 0x2d
'CafeOrCoffeeShop' => '0x2a0e', #Food - Cafe Diner 0x2a0e
'Bakery' => '0x2a05', #Food - Deli Bakery 0x2a05
'FastFoodRestaurant' => '0x2a07', #Food - Fast Food 0x2a07
'Restaurant' => '0x2a', #Food 0x2a
'FoodEstablishment' => '0x2a', #Food 0x2a
'IceCreamShop' => '0x2a', #Food 0x2a
'CivicStructure' => '0x3005', #Govt - Community Center 0x3005
'Courthouse' => '0x3004', #Govt - Court 0x3004
'FireStation' => '0x3008', #Govt - Fire stations 0x3008
'Hospital' => '0x3002', #Govt - Hospitals 0x3002
'PoliceStation' => '0x3001', #Govt - police 0x3001
'GovernmentOffice' => '0x3003', #Govt - Public Office Government 0x3003
'ChildCare' => '0x2c05', #Govt - School 0x2c05
'CollegeOrUniversity' => '0x2c05', #Govt - School 0x2c05
'ElementarySchool' => '0x2c05', #Govt - School 0x2c05
'HighSchool' => '0x2c05', #Govt - School 0x2c05
'MiddleSchool' => '0x2c05', #Govt - School 0x2c05
'Preschool' => '0x2c05', #Govt - School 0x2c05
'School' => '0x2c05', #Govt - School 0x2c05
'TouristInformationCenter' => '0x4c', #Information 0x4c
'Beach' => '0x6604', #Land - Beach 0x6604
'Mountain' => '0x6616', #Land - Summit 0x6616
'Cemetery' => '0x6403', #Manmade - Cemetery 0x6403
'Crematorium' => '0x6403', #Manmade - Cemetery 0x6403
'CivicStructure/Toilet' => '0x2f0c', #Recreation - Restroom Toilet 0x2f0c
'CivicStructure/BoatRamp' => '0x4700', #Marine - Boat Ramp 0x4700
'CivicStructure/PublicPhone' => '0x2f15', #Services - Telephone 0x2f15
'BankOrCreditUnion' => '0x2f06', #Services - Banks 0x2f06
'AutomatedTeller' => '0x2f06', #Services - Banks 0x2f06
'PostOffice' => '0x2f05', #Services - Post office 0x2f05
'TravelAgency' => '0x2f11', #Services - Travel agents 0x2f11
'HomeGoodsStore' => '0x2e', #Shopping 0x2e
'ClothingStore' => '0x2e07', #Shopping - Apparel 0x2e07
'MensClothingStore' => '0x2e07', #Shopping - Apparel 0x2e07
'ShoeStore' => '0x2e07', #Shopping - Apparel 0x2e07
'ComputerStore' => '0x2e0b', #Shopping - Computer Software 0x2e0b
'ElectronicsStore' => '0x2e0b', #Shopping - Computer Software 0x2e0b
'ConvenienceStore' => '0x2e06', #Shopping - Convenience Store 0x2e06
'DepartmentStore' => '0x2e01', #Shopping - Department Store 0x2e01
'OutletStore' => '0x2e03', #Shopping - General Merchandiser 0x2e03
'FurnitureStore' => '0x2e09', #Shopping - Home Furnishing 0x2e09
'GardenStore' => '0x2e08', #Shopping - House & Garden 0x2e08
'HardwareStore' => '0x2e08', #Shopping - House & Garden 0x2e08
'HomeAndConstructionBusiness' => '0x2f', #Services - Other 0x2f
'Pharmacy' => '0x2e05', #Shopping - Pharmacy 0x2e05
'ShoppingCenter' => '0x2e04', #Shopping - Shopping Center 0x2e04
'GroceryStore' => '0x2e02', #Shopping - Supermarkets 0x2e02
'BikeStore' => '0x2e', #Shopping 0x2e
'BookStore' => '0x2e', #Shopping 0x2e
'Florist' => '0x2e', #Shopping 0x2e
'HobbyShop' => '0x2e', #Shopping 0x2e
'JewelryStore' => '0x2e', #Shopping 0x2e
'LiquorStore' => '0x2e', #Shopping 0x2e
'MobilePhoneStore' => '0x2e', #Shopping 0x2e
'MovieRentalStore' => '0x2e', #Shopping 0x2e
'MusicStore' => '0x2e', #Shopping 0x2e
'OfficeEquipmentStore' => '0x2e', #Shopping 0x2e
'PawnShop' => '0x2e', #Shopping 0x2e
'PetStore' => '0x2e', #Shopping 0x2e
'SportingGoodsStore' => '0x2e', #Shopping 0x2e
'Store' => '0x2e', #Shopping 0x2e
'ToyStore' => '0x2e', #Shopping 0x2e
'WholesaleStore' => '0x2e', #Shopping 0x2e
'BowlingAlley' => '0x2d07', #Sport - Bowling 0x2d07
'HealthClub' => '0x2d0a', #Sport - Fitness Center 0x2d0a
'GolfCourse' => '0x2d05', #Sport - Golf 0x2d05
'SkiResort' => '0x2D06', #Sport - Skiing centre resort 0x2D06
'PublicSwimmingPool' => '0x2d09', #Sport - Swimming Pool (sports) 0x2d09
'ExerciseGym' => '0x2d00', #Sport 0x2d00
'SportsActivityLocation' => '0x2d00', #Sport 0x2d00
'SportsClub' => '0x2d00', #Sport 0x2d00
'TennisComplex' => '0x2d00', #Sport 0x2d00
'BusStation' => '0x2f08', #Transport - Ground transportation 0x2f08
'BusStop' => '0x2f08', #Transport - Ground transportation 0x2f08
'SubwayStation' => '0x2f08', #Transport - Ground transportation 0x2f08
'TaxiStand' => '0x2f08', #Transport - Ground transportation 0x2f08
'TrainStation' => '0x2f08', #Transport - Ground transportation 0x2f08
'Waterfall' => '0x6508', #Water - Waterfall 0x6508
'LakeBodyOfWater' => '0x650D', #Water Feature - Lake 0x650D
'AccountingService' => '0x2f', #Services - Other 0x2f
'AdultEntertainment' => '0x2f', #Services - Other 0x2f
'AnimalShelter' => '0x2f', #Services - Other 0x2f
'Aquarium' => '0x2f', #Services - Other 0x2f
'ArtGallery' => '0x2f', #Services - Other 0x2f
'Attorney' => '0x2f', #Services - Other 0x2f
'BeautySalon' => '0x2f', #Services - Other 0x2f
'BodyOfWater' => '0x2f', #Services - Other 0x2f
'Brewery' => '0x2f', #Services - Other 0x2f
'Canal' => '0x2f', #Services - Other 0x2f
'CityHall' => '0x2f', #Services - Other 0x2f
'Continent' => '0x2f', #Services - Other 0x2f
'Corporation' => '0x2f', #Services - Other 0x2f
'DaySpa' => '0x2f', #Services - Other 0x2f
'DefenceEstablishment' => '0x2f', #Services - Other 0x2f
'Dentist' => '0x2f', #Services - Other 0x2f
'DryCleaningOrLaundry' => '0x2f', #Services - Other 0x2f
'EducationalOrganization' => '0x2f', #Services - Other 0x2f
'Electrician' => '0x2f', #Services - Other 0x2f
'Embassy' => '0x2f', #Services - Other 0x2f
'EmergencyService' => '0x2f', #Services - Other 0x2f
'EmploymentAgency' => '0x2f', #Services - Other 0x2f
'EventVenue' => '0x2f', #Services - Other 0x2f
'FinancialService' => '0x2f', #Services - Other 0x2f
'GeneralContractor' => '0x2f', #Services - Other 0x2f
'GovernmentBuilding' => '0x2f', #Services - Other 0x2f
'GovernmentOrganization' => '0x3003', #Govt - Public Office Government 0x3003
'HairSalon' => '0x2f', #Services - Other 0x2f
'HealthAndBeautyBusiness' => '0x2f', #Services - Other 0x2f
'HousePainter' => '0x2f', #Services - Other 0x2f
'HVACBusiness' => '0x2f', #Services - Other 0x2f
'InsuranceAgency' => '0x2f', #Services - Other 0x2f
'InternetCafe' => '0x2f', #Services - Other 0x2f
'Landform' => '0x2f', #Services - Other 0x2f
'LegislativeBuilding' => '0x2f', #Services - Other 0x2f
'LocalBusiness' => '0x2f', #Services - Other 0x2f
'Locksmith' => '0x2f', #Services - Other 0x2f
'MedicalClinic' => '0x2f', #Services - Other 0x2f
'MedicalOrganization' => '0x2f', #Services - Other 0x2f
'MovingCompany' => '0x2f', #Services - Other 0x2f
'MusicVenue' => '0x2f', #Services - Other 0x2f
'NailSalon' => '0x2f', #Services - Other 0x2f
'NGO' => '0x2f', #Services - Other 0x2f
'Notary' => '0x2f', #Services - Other 0x2f
'OceanBodyOfWater' => '0x2f', #Services - Other 0x2f
'Optician' => '0x2f', #Services - Other 0x2f
'Physician' => '0x2f', #Services - Other 0x2f
'Playground' => '0x2f', #Services - Other 0x2f
'Plumber' => '0x2f', #Services - Other 0x2f
'Pond' => '0x2f', #Services - Other 0x2f
'ProfessionalService' => '0x2f', #Services - Other 0x2f
'RadioStation' => '0x2f', #Services - Other 0x2f
'RealEstateAgent' => '0x2f', #Services - Other 0x2f
'RecyclingCenter' => '0x2f', #Services - Other 0x2f
'Reservoir' => '0x2f', #Services - Other 0x2f
'RiverBodyOfWater' => '0x2f', #Services - Other 0x2f
'RoofingContractor' => '0x2f', #Services - Other 0x2f
'SeaBodyOfWater' => '0x2f', #Services - Other 0x2f
'SelfStorage' => '0x2f', #Services - Other 0x2f
'TattooParlor' => '0x2f', #Services - Other 0x2f
'TelevisionStation' => '0x2f', #Services - Other 0x2f
'VeterinaryCare' => '0x2f', #Services - Other 0x2f
'Volcano' => '0x2f', #Services - Other 0x2f
'Thing/NEC' => '0x2f' #Services - Other 0x2f
}

# #####################
def assignCategoryFromZenbuCategory(data)
  primary_zenbu_category = data['categories'].split(' ').first rescue ''
	if primary_zenbu_category.empty? && GUESS_FROM_TAGS && (guessed_category = assignCategoryFromZenbuTags(data)) then
    @reporting['category_from_zenbu_tags']+=1
    @debug.print "#{data['zid']}\tcategory_from_zenbu_tags\t#{data['name']}\t#{data['tags']}\t#{guessed_category}\n" if @debug
    return guessed_category
  elsif @zenbu_category_to_garmin_category.has_key?(primary_zenbu_category) then
    @reporting['category_from_zenbu_category']+=1
    return @zenbu_category_to_garmin_category[primary_zenbu_category]
  else
    @reporting['category_from_zenbu_default']+=1
    return DEFAULT_CATEGORY
  end
end

#default category if the Zenbu category is missing from our lookup table
DEFAULT_CATEGORY = '0x2f'

# #####################
def assignCategoryFromZenbuTags(data)
#attempt to best guess a POI type code from name and tags
		tags = data['tags']
		name = data['name']
		
		if tags =~ /toilet/i
			category = '0x2f0c'
		elsif tags =~ /restaurant/i || name =~ /restaurant/i
			if tags =~ /(thai|japanese)/i
				category = '0x2a02'
			elsif tags =~ /chinese/i
				category = '0x2a04'
			elsif tags =~ /italian/i
				category = '0x2a08'
			elsif tags =~ /seafood/i
				category = '0x2a0b'
			elsif tags =~ /french/i
				category = '0x2a0f'
			else
				category = '0x2a'
			end
		elsif tags =~ /b\&b/i
			category = '0x2b02'
		elsif tags =~ /motel/i
			category = '0x2b01'
		elsif tags =~ /hotel/i
			category = '0x2b01'
		elsif tags =~ /accommodation/i
			category = '0x2b00'
		elsif tags =~ /Camping/i
			category = '0x2b03'
		elsif tags =~ /bakery/i
			category = '0x2a05'
		elsif tags =~ /museum/i
			category = '0x2c02'
		elsif tags =~ /Funeral director/i
			category = '0x2f'
		elsif tags =~ /library/i
			category = '0x2c03'
		elsif tags =~ /(\bbank\b|\batm\b)/i
			category = '0x2f06'
		elsif tags =~ /winery/i
			category = '0x2c0a'
		elsif tags =~ /travel agent/i
			category = '0x2f11'
		elsif tags =~ /car rental/i
			category = '0x2F02'
		elsif tags =~ /\bbar\b/i
			category = '0x2d02'
		elsif tags =~ /cafe/i #cafes should look for é too
			category = '0x2a0e'
		elsif tags =~ /parking/i
			category = '0x2f0b'
		elsif tags =~ /marina/i
			category = '0x2F09'
		elsif tags =~ /\b(church|mosque)\b/i
			category = '0x6404'
		elsif tags =~ /\bpark\b/i
			category = '0x2c06'
		elsif tags =~ /Speed Camera/i
			category = '00 Not For Maps'
		elsif tags =~ /swimming pool/i
			category = '0x2d09'
		elsif tags =~ /Petrol Station/i
			category = '0x2f01'
		elsif tags =~ /supermarket/i
			category = '0x2e02'
		elsif tags =~ /DOC Backcountry Hut/i
			category = '0x6402'
		elsif tags =~ /cemetery/i
			category = '0x6403'
		elsif tags =~ /fast food/i
			category = '0x2a07'
		elsif tags =~ /pizza/i
			category = '0x2a0a'
		elsif tags =~ /visitor information/i
			category = '0x4c'
		elsif tags =~ /antique/i
			category = '0x2e'
		elsif tags =~ /fresh fruit/i
			category = '0x2e'
		elsif tags =~ /butcher/i
			category = '0x2e'
		elsif tags =~ /liquor.*beer/i
			category = '0x2e'
		elsif tags =~ /\b(clothes|footwear|shoes|Menswear)\b/i
			category = '0x2e07'
		elsif tags =~ /\b(furniture|beds)\b/i
			category = '0x2e09'
		elsif tags =~ /convenience store/i
			category = '0x2e'
		elsif tags =~ /superette/i
			category = '0x2e06'
		elsif tags =~ /boat ramp/i
			category = '0x4700'
		elsif tags =~ /hairdresser/i
			category = '0x2f'
		elsif tags =~ /car dealer/i
			category = '0x2F07'
		elsif tags =~ /public phone box/i
			category = '0x2f15'
		elsif tags =~ /ski field/i
			category = '0x2D06'
		elsif tags =~ /take-?away/i # || name =~ /take[\s-]?away/i #name or tags has takeaway
			category = '0x2a07'
		elsif tags =~ /pharmacy/i
			category = '0x2e05'
		elsif tags =~ /clothing/i
			category = '0x2e07'
		elsif tags =~ /rest area/i
			category = '0x4a00'
		else
			category = nil
		end
		
		return category
end

# #####################
@garmin_category_descriptions = {
'0x2a' => 'Food',
'0x2a02' => 'Food - Asian',
'0x2a03' => 'Food - Barbecue',
'0x2a04' => 'Food - Chinese',
'0x2a05' => 'Food - Deli Bakery',
'0x2a07' => 'Food - Fast Food',
'0x2a08' => 'Food - Italian',
'0x2a09' => 'Food - Mexican',
'0x2a0a' => 'Food - Pizza',
'0x2a0b' => 'Food - Seafood',
'0x2a0d' => 'Food - Bagel Donuts',
'0x2a0e' => 'Food - Cafe Diner',
'0x2a0f' => 'Food - French',
'0x2b00' => 'Accommodation',
'0x2b01' => 'Accommodation - Hotel - Motel',
'0x2b02' => 'Accommodation - Bed & Breakfast Inn',
'0x2b03' => 'Accommodation - Camping RV Park',
'0x2c00' => 'Attractions',
'0x2c01' => 'Attractions - Amusement Theme Park',
'0x2c02' => 'Attractions - Museum History',
'0x2c03' => 'Attractions - Libraries',
'0x2c04' => 'Attractions - Landmark',
'0x2c05' => 'Govt - School',
'0x2c06' => 'Attractions - Park',
'0x2c07' => 'Attractions - Zoo',
'0x2c08' => 'Attractions - Arena Stadium Track Raceway',
'0x2c0a' => 'Attractions - Vineyard Winery',
'0x2d' => 'Entertainment',
'0x2d00' => 'Sport',
'0x2d01' => 'Entertainment - Theatre',
'0x2d02' => 'Entertainment - Bar',
'0x2d03' => 'Entertainment - Cinema',
'0x2D04' => 'Entertainment - Casino',
'0x2d05' => 'Sport - Golf',
'0x2D06' => 'Sport - Skiing centre resort',
'0x2d07' => 'Sport - Bowling',
'0x2d08' => 'Sport - Ice Skating',
'0x2d09' => 'Sport - Swimming Pool (sports)',
'0x2d0a' => 'Sport - Fitness Center',
'0x2e' => 'Shopping',
'0x2e01' => 'Shopping - Department Store',
'0x2e02' => 'Shopping - Supermarkets',
'0x2e03' => 'Shopping - General Merchandiser',
'0x2e04' => 'Shopping - Shopping Center',
'0x2e05' => 'Shopping - Pharmacy',
'0x2e06' => 'Shopping - Convenience Store',
'0x2e07' => 'Shopping - Apparel',
'0x2e08' => 'Shopping - House & Garden',
'0x2e09' => 'Shopping - Home Furnishing',
'0x2e0b' => 'Shopping - Computer Software',
'0x2f' => 'Services - Other',
'0x2f01' => 'Auto - Fuel petrol stations',
'0x2F02' => 'Auto - Car Rental',
'0x2f03' => 'Auto - Repair',
'0x2f04' => 'Aviation - Airport',
'0x2f05' => 'Services - Post office',
'0x2f06' => 'Services - Banks',
'0x2F07' => 'Auto - Car Dealer Autoparts',
'0x2f08' => 'Transport - Ground transportation',
'0x2F09' => 'Marine - Marina',
'0x2f0b' => 'Auto - Parking',
'0x2f0c' => 'Recreation - Restroom Toilet',
'0x2f0d' => 'Auto - Automobile Club',
'0x2F0E' => 'Auto - Car Wash',
'0x2f0f' => 'GPS Garmin Dealer',
'0x2f11' => 'Services - Travel agents',
'0x2f15' => 'Services - Telephone',
'0x3001' => 'Govt - police',
'0x3002' => 'Govt - Hospitals',
'0x3003' => 'Govt - Public Office Government',
'0x3004' => 'Govt - Court',
'0x3005' => 'Govt - Community Center',
'0x3008' => 'Govt - Fire stations',
'0x4700' => 'Marine - Boat Ramp',
'0x4a00' => 'Recreation - Rest Area Picnic Area',
'0x4b00' => 'First Aid Station',
'0x4c' => 'Information',
'0x5200' => 'Recreation - Scenic Area',
'0x5400' => 'Sport - Swimming Area (recreation)',
'0x5903' => 'Aviation - Airport Small',
'0x5904' => 'Aviation - Heliport',
'0x6400' => 'Man-made place',
'0x6402' => 'Man-made - Building',
'0x6403' => 'Manmade - Cemetery',
'0x6404' => 'Church place of worship',
'0x6412' => 'Trailhead',
'0x6508' => 'Water - Waterfall',
'0x650D' => 'Water Feature - Lake',
'0x6604' => 'Land - Beach',
'0x6616' => 'Land - Summit'
}
